### ISSUE TITLE
Slack link

### ISSUE THREAD

**Issue by jstoja** [ossf/foundation#15]
Hello @LindsayLF,

I wanted to add the Slack community link to this page, but the [actual link ](https://openssf.slack.com/join/shared_invite/zt-kjkth2mc-ELii08LEup2urk8Suy0Q1Q#/)from the website is not working:
![Screenshot from 2021-01-29 13-24-13](https://user-images.githubusercontent.com/1444415/106274964-64de2180-6235-11eb-9134-3d0d4ff677f8.png)

Would you have a new link so it can be added here and fixed on the website?

Best,
Julien

**Comment by LindsayLF** [comment]
Hi @jstoja - good catch, the re-direct has now been updated! https://slack.openssf.org/
